sequenceDiagram
    participant Client
    participant UserService
    participant UserRepository

    Client ->> UserService: Create User
    UserService ->> UserRepository: Add User with Status Active
    UserRepository ->> UserService: User
    UserService ->> Client : User