sequenceDiagram
    participant Client
    participant UserService
    participant UserRepository

    Client ->> UserService: GET User Role
    alt Authorization header is valid
        UserService ->> UserRepository: findByUsernameAndPassword(username, password)
    alt User found
        UserRepository -->> UserService: Role
        UserService -->> Client: Role
    else User not found
        UserService --x Client: UserDoesNotExistsException
    end
    else Invalid authorization header
        UserService --x Client: InvalidHeaderAuthorizationException
    end