sequenceDiagram
    participant Client
    participant UserService
    participant UserRepository

    Client ->> UserService: Patch User
    UserService -->> UserRepository : findUserByUsernameAndPassword
    alt Authorization User Exists
        UserRepository -->> UserService : User

        alt Authorization User is the same
            UserService ->> UserRepository: Patch User properties
            UserRepository -->> UserService: User
            UserService -->> Client : User
        end
        alt Authorization User is not valid
            UserService -->> Client: UserDoesNotHavePermissionsException
        end
        else Authorization User Does Not Exists

            UserRepository -->> UserService: DataIntegrityViolationException
            UserService -->> Client: InvalidHeaderAuthorizationException
    end


