package com.mindera.api;

import com.mindera.api.domain.*;
import com.mindera.api.enums.Gender;
import com.mindera.api.enums.UserStatus;

public enum Accounts {
    ADMIN_ACTIVE_MALE_ACCOUNT(User.builder()
            .id(1L)
            .username("Admin")
            .vatNumber("12345")
            .age(30)
            .gender(Gender.MALE)
            .contacts(Contacts.builder()
                    .email("admin@mindera.com")
                    .phoneNumber("911 111 111")
                    .build())
            .paymentMethods(PaymentMethods.builder()
                    .cardHolderName("Admin")
                    .cardNumber(4111111111111111L)
                    .expireDate("11/02")
                    .cvv(123L)
                    .build())
            .address(Address.builder()
                    .addressLine("Avenue")
                    .city("Porto")
                    .postalCode("4400-000")
                    .country("Portugal")
                    .build())
            .password("password")
            .role(Role.ADMIN)
            .status(UserStatus.ACTIVE)
            .build()),

    CUSTOMER_ACTIVE_MALE_ACCOUNT(User.builder()
            .id(2L)
            .username("Customer")
            .vatNumber("1")
            .age(27)
            .gender(Gender.MALE)
            .contacts(Contacts.builder()
                    .email("customer1@mindera.com")
                    .phoneNumber("911 111 111")
                    .build())
            .paymentMethods(PaymentMethods.builder()
                    .cardHolderName("Customer")
                    .cardNumber(4111111111111111L)
                    .expireDate("11/02")
                    .cvv(123L)
                    .build())
            .address(Address.builder()
                    .addressLine("Avenue")
                    .city("Porto")
                    .postalCode("4400-000")
                    .country("Portugal")
                    .build())
            .password("password")
            .role(Role.CUSTOMER)
            .status(UserStatus.ACTIVE)
            .build()),

    CUSTOMER_WITHOUT_STATUS_MALE_ACCOUNT(User.builder()
            .id(2L)
            .username("Customer")
            .vatNumber("1")
            .age(27)
            .gender(Gender.MALE)
            .contacts(Contacts.builder()
                    .email("customer1@mindera.com")
                    .phoneNumber("911 111 111")
                    .build())
            .paymentMethods(PaymentMethods.builder()
                    .cardHolderName("Customer")
                    .cardNumber(4111111111111111L)
                    .expireDate("11/02")
                    .cvv(123L)
                    .build())
            .address(Address.builder()
                    .addressLine("Avenue")
                    .city("Porto")
                    .postalCode("4400-000")
                    .country("Portugal")
                    .build())
            .password("password")
            .role(Role.CUSTOMER)
            .build()),

    CUSTOMER_WITHOUT_VAT_NUMBER_MALE_ACCOUNT(User.builder()
            .id(2L)
            .username("Customer")
            .age(27)
            .gender(Gender.MALE)
            .contacts(Contacts.builder()
                    .email("customer1@mindera.com")
                    .phoneNumber("911 111 111")
                    .build())
            .paymentMethods(PaymentMethods.builder()
                    .cardHolderName("Customer")
                    .cardNumber(4111111111111111L)
                    .expireDate("11/02")
                    .cvv(123L)
                    .build())
            .address(Address.builder()
                    .addressLine("Avenue")
                    .city("Porto")
                    .postalCode("4400-000")
                    .country("Portugal")
                    .build())
            .password("password")
            .role(Role.CUSTOMER)
            .build()),

    CUSTOMER_ACTIVE_FEMALE_ACCOUNT(User.builder()
            .id(3L)
            .username("Customer")
            .vatNumber("3")
            .age(27)
            .gender(Gender.FEMALE)
            .contacts(Contacts.builder()
                    .email("customer3@mindera.com")
                    .phoneNumber("911 111 111")
                    .build())
            .paymentMethods(PaymentMethods.builder()
                    .cardHolderName("Customer")
                    .cardNumber(4111111111111111L)
                    .expireDate("11/02")
                    .cvv(123L)
                    .build())
            .address(Address.builder()
                    .addressLine("Avenue")
                    .city("Porto")
                    .postalCode("4400-000")
                    .country("Portugal")
                    .build())
            .password("password")
            .role(Role.CUSTOMER)
            .status(UserStatus.ACTIVE)
            .build());

    private final User user;

    Accounts(User user) {
        this.user = user;
    }

    public User getUser() {
        return user;
    }
}
