spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    show-sql: ${SQL_SHOW}
    hibernate:
      ddl-auto: ${DLL_AUTO}
  rabbitmq: 
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}

springdoc:
  show-actuator: true

server:
  port: 8082